
--- CREATE TABLE

CREATE TABLE `USER_INFO` (
	`U_IDX`	NUMBER(5)	NOT NULL,
	`U_ID`	VARCHAR2(30)	NULL,
	`PWD`	VARCHAR2(30)	NULL,
	`PHONE`	VARCHAR2(20)	NULL,
	`EMAIL`	VARCHAR2(30)	NULL,
	`BIRTH`	VARCHAR2(30)	NULL,
	`NAME`	VARCHAR2(20)	NULL,
	`BIO`	VARCHAR2(20)	NULL,
	`U_PIC`	VARCHAR2(300)	NULL
);

CREATE TABLE `FOLLOWER` (
	`ER_IDX`	NUMBER(5)	NOT NULL,
	`TO_IDX`	NUMBER(5)	NULL,
	`FROM_IDX`	NUMBER(5)	NULL
);

CREATE TABLE `FOLLOWING` (
	`ING_IDX`	NUMBER(5)	NOT NULL,
	`FROM_IDX`	NUMBER(5)	NULL,
	`TO_IDX`	NUMBER(5)	NULL
);

CREATE TABLE `FEED` (
	`F_IDX`	NUMBER(5)	NOT NULL,
	`REGDATE`	VARCHAR2(30)	NULL,
	`CONTENT`	VARCHAR2(300)	NULL,
	`U_IDX`	NUMBER(5)	NOT NULL,
	`U_LIKE`	NUMBER(5)	NULL,
	`F_PIC`	VARCHAR2(300)	NULL
);

CREATE TABLE `COMM` (
	`CO_IDX`	NUMBER(5)	NOT NULL,
	`REGDATE`	VARCHAR2(30)	NULL,
	`COMM`	VARCHAR2(100)	NULL,
	`F_IDX`	NUMBER(5)	NOT NULL
);

CREATE TABLE `LIKE_LIST` (
	`L_IDX`	NUMBER(5)	NOT NULL,
	`F_IDX`	NUMBER(5)	NOT NULL
);

ALTER TABLE `USER_INFO` ADD CONSTRAINT `PK_USER_INFO` PRIMARY KEY (
	`U_IDX`
);

ALTER TABLE `FOLLOWER` ADD CONSTRAINT `PK_FOLLOWER` PRIMARY KEY (
	`ER_IDX`
);

ALTER TABLE `FOLLOWING` ADD CONSTRAINT `PK_FOLLOWING` PRIMARY KEY (
	`ING_IDX`
);

ALTER TABLE `FEED` ADD CONSTRAINT `PK_FEED` PRIMARY KEY (
	`F_IDX`
);

ALTER TABLE `COMM` ADD CONSTRAINT `PK_COMM` PRIMARY KEY (
	`CO_IDX`
);

ALTER TABLE `LIKE_LIST` ADD CONSTRAINT `PK_LIKE_LIST` PRIMARY KEY (
	`L_IDX`
);



-----------CREATE SEQUENCE----------------------

CREATE SEQUENCE USER_INFO_SEQ
INCREMENT BY 1
MINVALUE 1
;

CREATE SEQUENCE FEED_SEQ
INCREMENT BY 1
MINVALUE 1
;

CREATE SEQUENCE COMM_SEQ
INCREMENT BY 1
MINVALUE 1
;
CREATE SEQUENCE FOLLOWER_SEQ
INCREMENT BY 1
MINVALUE 1
;
CREATE SEQUENCE FOLLOWING_SEQ
INCREMENT BY 1
MINVALUE 1
;
CREATE SEQUENCE LIKE_SEQ
INCREMENT BY 1
MINVALUE 1
;

---------------------


--나의 메인피드(팔로잉과 나의 게시물)
select distinct fd.f_idx, fd.regdate, fd.content, fd.u_idx, fd.u_like, fd.f_pic
from feed fd,
(select * from following where from_idx = '내 회원번호') fing
where fd.u_idx = fing.to_idx
or fd.u_idx = '내 회원번호'
;

-- 내 계정(내가 올린 게시물)
select * from feed where u_idx = '내 회원번호';

--id와 bio 검색(회원 찾기)
select * from user_info
where u_id like '%검색어%' or bio like '%검색어%';

-- 내용 검색(게시글 찾기)
select * from feed
where content like '%검색어%';












