
--데이터 추가
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 11,4);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 11,5);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 11,6);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 11,7);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 11,8);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 11,9);

INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 4,9);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 4,11);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 4,12);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 5,6);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 5,7);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 5,8);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 6,8);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 6,9);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 6,11);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 7,4);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 7,5);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 7,6);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 8,4);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 8,12);
INSERT INTO FOLLOW (ER_IDX, TO_IDX, FROM_IDX) VALUES (FOLLOWER_SEQ.NEXTVAL, 8,7);



--나의 메인피드(팔로잉과 나의 게시물)
select distinct fd.f_idx, fd.regdate, fd.content, fd.u_idx, fd.u_like, fd.f_pic
from feed fd,
(select * from following where from_idx = '내 회원번호') fing
where fd.u_idx = fing.to_idx
or fd.u_idx = '내 회원번호'
;

-- 내 계정(내가 올린 게시물)
select * from feed where u_idx = '내 회원번호';

--id와 bio 검색(회원 찾기)
select * from user_info
where u_id like '%검색어%' or bio like '%검색어%';

-- 내용 검색(게시글 찾기)
select * from feed
where content like '%검색어%';












